---
title: "Airbnb analyses NY"
output: html_notebook
---

#Load libraries
```{r}

library("tidyverse")
library("broom")
library("caret")
library("knitr")
library("car")
library("kableExtra")
library("tidyr")
library("psych")
library("dplyr")
library("utf8")
library("sentimentr")
library("ggpubr")
library("corrplot")
library("data.table")
library("tidycensus")
library("faraway")
library("ISLR")
library("Metrics")

```

#load files
```{r}

listings_apr18 <- read_csv("New York/Listings/listings_apr18.csv")
listings_may18 <- read_csv("New York/Listings/listings_may18.csv")
listings_jun18 <- read_csv("New York/Listings/listings_jun18.csv")
listings_jul18 <- read_csv("New York/Listings/listings_jul18.csv")
listings_aug18 <- read_csv("New York/Listings/listings_aug18.csv")
listings_sep18 <- read_csv("New York/Listings/listings_sep18.csv")
listings_oct18 <- read_csv("New York/Listings/listings_oct18.csv")
listings_nov18 <- read_csv("New York/Listings/listings_nov18.csv")
listings_dec18 <- read_csv("New York/Listings/listings_dec18.csv")
listings_jan19 <- read_csv("New York/Listings/listings_jan19.csv")
listings_feb19 <- read_csv("New York/Listings/listings_feb19.csv")
listings_mar19 <- read_csv("New York/Listings/listings_mar19.csv")

calendar <- read_csv("New York/calendar.csv")
calendar_1 <- read_csv("New York/calendar_1.csv")
calendar_2 <- read_csv("New York/calendar_2.csv")
calendar_3 <- read_csv("New York/calendar_3.csv")
calendar_4 <- read_csv("New York/calendar_4.csv")
calendar_5 <- read_csv("New York/calendar_5.csv")
calendar_6 <- read_csv("New York/calendar_6.csv")
calendar_7 <- read_csv("New York/calendar_7.csv")
calendar_8 <- read_csv("New York/calendar_8.csv")
calendar_9 <- read_csv("New York/calendar_9.csv")
calendar_10 <- read_csv("New York/calendar_10.csv")
calendar_11 <- read_csv("New York/calendar_11.csv")

```


```{r}

april_price <- na.omit(calendar)

april <- subset(april_price, date> "2018-04-01" & date < "2018-04-30")

april$price <- parse_number(april$price)

mean_price_april <- aggregate(april[, 4], list(april$listing_id), mean)

mean_price_april <- mean_price_april %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_apr18 <- merge(listings_apr18, mean_price_april, all = TRUE)

```


```{r}

may_price <- na.omit(calendar_1)

may <- subset(may_price, date> "2018-05-01" & date < "2018-05-31")

may$price <- parse_number(may$price)

mean_price_may <- aggregate(may[, 4], list(may$listing_id), mean)

mean_price_may <- mean_price_may %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_may18 <- merge(listings_may18, mean_price_may, all = TRUE)

```

```{r}

jun_price <- na.omit(calendar_2)

jun <- subset(jun_price, date> "2018-06-01" & date < "2018-06-30")

jun$price <- parse_number(jun$price)

mean_price_jun <- aggregate(jun[, 4], list(jun$listing_id), mean)

mean_price_jun <- mean_price_jun %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_jun18 <- merge(listings_jun18, mean_price_jun, all = TRUE)

```


```{r}

jul_price <- na.omit(calendar_3)

jul <- subset(jul_price, date> "2018-07-01" & date < "2018-07-31")

jul$price <- parse_number(jul$price)

mean_price_jul <- aggregate(jul[, 4], list(jul$listing_id), mean)

mean_price_jul <- mean_price_jul %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_jul18 <- merge(listings_jul18, mean_price_jul, all = TRUE)


```



```{r}

aug_price <- na.omit(calendar_4)

aug <- subset(aug_price, date> "2018-08-01" & date < "2018-08-31")

aug$price <- parse_number(aug$price)

mean_price_aug <- aggregate(aug[, 4], list(aug$listing_id), mean)

mean_price_aug <- mean_price_aug %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_aug18 <- merge(listings_aug18, mean_price_aug, all = TRUE)


```


```{r}

sep_price <- na.omit(calendar_5)

sep <- subset(sep_price, date> "2018-09-01" & date < "2018-09-30")

sep$price <- parse_number(sep$price)

mean_price_sep <- aggregate(sep[, 4], list(sep$listing_id), mean)

mean_price_sep <- mean_price_sep %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_sep18 <- merge(listings_sep18, mean_price_sep, all = TRUE)


```



```{r}

oct_price <- na.omit(calendar_6)

oct <- subset(oct_price, date> "2018-10-01" & date < "2018-10-31")

oct$price <- parse_number(oct$price)

mean_price_oct <- aggregate(oct[, 4], list(oct$listing_id), mean)

mean_price_oct <- mean_price_oct %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_oct18 <- merge(listings_oct18, mean_price_oct, all = TRUE)


```


```{r}

nov_price <- na.omit(calendar_7)

nov <- subset(nov_price, date> "2018-11-01" & date < "2018-11-30")

nov$price <- parse_number(nov$price)

mean_price_nov <- aggregate(nov[, 4], list(nov$listing_id), mean)

mean_price_nov <- mean_price_nov %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_nov18 <- merge(listings_nov18, mean_price_nov, all = TRUE)


```


```{r}

dec_price <- na.omit(calendar_8)

dec <- subset(dec_price, date> "2018-12-01" & date < "2018-12-31")

dec$price <- parse_number(dec$price)

mean_price_dec <- aggregate(dec[, 4], list(dec$listing_id), mean)

mean_price_dec <- mean_price_dec %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_dec18 <- merge(listings_dec18, mean_price_dec, all = TRUE)


```


```{r}

jan_price <- na.omit(calendar_9)

jan <- subset(jan_price, date> "2019-01-01" & date < "2019-01-31")

jan$price <- parse_number(jan$price)

mean_price_jan <- aggregate(jan[, 4], list(jan$listing_id), mean)

mean_price_jan <- mean_price_jan %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_jan19 <- merge(listings_jan19, mean_price_jan, all = TRUE)


```



```{r}

feb_price <- na.omit(calendar_10)

feb <- subset(feb_price, date> "2019-02-01" & date < "2019-02-28")

feb$price <- parse_number(feb$price)

mean_price_feb <- aggregate(feb[, 4], list(feb$listing_id), mean)

mean_price_feb <- mean_price_feb %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_feb19 <- merge(listings_feb19, mean_price_feb, all = TRUE)


```



```{r}

mar_price <- na.omit(calendar_11)

mar <- subset(mar_price, date> "2019-03-01" & date < "2019-03-31")

mar$price <- parse_number(mar$price)

mean_price_mar <- aggregate(mar[, 4], list(mar$listing_id), mean)

mean_price_mar <- mean_price_mar %>% 
  rename(
    mean_price = price,
    id = Group.1)

listings_mar19 <- merge(listings_mar19, mean_price_mar, all = TRUE)


```


```{r}
#Combine both NY dataframes with one having 96 variables and one having 106 variables 

head(listings_feb19)

airbnb_oldcolumn <- rbind(listings_apr18, listings_may18, listings_jun18, listings_jul18, listings_aug18, listings_sep18, listings_oct18, listings_nov18, listings_dec18)
airbnb_newcolumn <- rbind(listings_jan19, listings_feb19, listings_mar19)
airbnb_newcolumn <- mutate(airbnb_newcolumn, 
                           minimum_minimum_nights = NULL,
                           maximum_minimum_nights = NULL,
                           minimum_maximum_nights = NULL,
                           maximum_maximum_nights = NULL,
                           minimum_nights_avg_ntm = NULL,
                           maximum_nights_avg_ntm = NULL,
                           number_of_reviews_ltm = NULL,
                           calculated_host_listings_count_entire_homes = NULL,
                           calculated_host_listings_count_private_rooms = NULL,
                           calculated_host_listings_count_shared_rooms = NULL)


airbnb_ny <- rbind(airbnb_newcolumn, airbnb_oldcolumn)

#save new NY datafile
write.csv(airbnb_ny, "airbnb dataset new york.csv")
```



























